package llm

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"time"

	"github.com/jnb666/agent-go/util"
	"github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/packages/respjson"
	"github.com/openai/openai-go/v3/shared"
)

// Message is a single message either generated by or sent to the model.
// Role may be "system", "user", "assistant" or "tool".
type Message struct {
	Role       string     `json:"role"`
	Content    string     `json:"content"`
	Reasoning  string     `json:"reasoning,omitzero"`
	ToolCalls  []ToolCall `json:"tool_calls,omitzero"`
	ToolCallID string     `json:"tool_call_id,omitzero"`
}

// Tool call parameters generated by the model included in assistant message.
type ToolCall struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// New message generated by the model with additional stats.
// If no error then FinishReason will be either "stop" or "tool_calls".
type ChatCompletion struct {
	Message      Message
	FinishReason string
	Stats        Stats
}

// Token usage stats, execution time and optional timing stats for llama.cpp
type Stats struct {
	PromptTokens     int
	PromptCached     int
	PromptMsec       float64
	CompletionTokens int
	CompletionMsec   float64
	TotalMsec        float64
}

type timings struct {
	PromptCached   int     `json:"cache_n"`
	PromptMsec     float64 `json:"prompt_ms"`
	CompletionMsec float64 `json:"predicted_ms"`
}

func (c Stats) String() string {
	s := fmt.Sprintf("prompt: %d tokens", c.PromptTokens)
	if c.PromptCached != 0 {
		s += fmt.Sprintf(" (%d cached)", c.PromptCached)
	}
	if c.PromptMsec != 0 {
		s += fmt.Sprintf(" at %.1f tps", 1000*float64(c.PromptTokens)/(c.PromptMsec))
	}
	s += fmt.Sprintf("  gen: %d tokens", c.CompletionTokens)
	if c.CompletionMsec != 0 {
		s += fmt.Sprintf(" at %.1f tps", 1000*float64(c.CompletionTokens)/(c.CompletionMsec))
	}
	return s
}

// Send a chat conversation to the model and return the next completion message. Any options given override those in SetOptions.
// The returned ChatCompletion may either contain the final content or one or more tool function calls.
func (m *Model) Generate(ctx context.Context, messages []Message, opts ...Option) (r ChatCompletion, err error) {
	defer func(start time.Time) {
		r.Stats.TotalMsec = time.Since(start).Seconds() * 1000
	}(time.Now())

	config := m.config.Clone()
	for _, opt := range opts {
		opt(&config)
	}
	req, err := m.newRequest(config, messages)
	if err != nil {
		return r, err
	}
	// call chat completions endpoint
	var resp *openai.ChatCompletion
	var acc accumulator
	if m.streaming {
		acc, err = m.generateStream(ctx, req)
		resp = &acc.ChatCompletion
	} else {
		resp, err = m.client.Chat.Completions.New(ctx, req)
	}

	// check for context cancellation
	if errors.Is(err, context.Canceled) {
		r.FinishReason = "cancelled"
	} else if errors.Is(err, context.DeadlineExceeded) {
		r.FinishReason = "deadline_exceeded"
	}

	// check have a response
	if resp == nil {
		return r, err
	}
	if len(resp.Choices) == 0 {
		return r, getError(resp.RawJSON())
	}

	// extract returned message
	errs := []error{err}
	if resp.Choices[0].FinishReason != "" {
		r.FinishReason = resp.Choices[0].FinishReason
	}
	msg := resp.Choices[0].Message
	r.Message.Role = "assistant"
	r.Message.Content = msg.Content + msg.Refusal
	if m.streaming {
		r.Message.Reasoning = acc.reasoning
	} else if fld, ok := msg.JSON.ExtraFields[m.reasoning]; ok {
		r.Message.Reasoning, err = strconv.Unquote(fld.Raw())
		errs = append(errs, err)
	}
	for _, call := range msg.ToolCalls {
		if call.Type == "function" {
			fn := ToolCall{ID: call.ID, Name: call.Function.Name, Arguments: call.Function.Arguments}
			r.Message.ToolCalls = append(r.Message.ToolCalls, fn)
		}
	}

	// extract stats from response
	if fld, ok := resp.JSON.ExtraFields["timings"]; ok && fld.Raw() != "" {
		var t timings
		err = json.Unmarshal([]byte(fld.Raw()), &t)
		r.Stats.PromptCached = t.PromptCached
		r.Stats.PromptMsec = t.PromptMsec
		r.Stats.CompletionMsec = t.CompletionMsec
		errs = append(errs, err)
	}
	r.Stats.PromptTokens = int(resp.Usage.PromptTokens)
	r.Stats.CompletionTokens = int(resp.Usage.CompletionTokens)
	return r, errors.Join(errs...)
}

func (m *Model) generateStream(ctx context.Context, req openai.ChatCompletionNewParams) (acc accumulator, err error) {
	req.StreamOptions = openai.ChatCompletionStreamOptionsParam{IncludeUsage: openai.Bool(true)}
	stream := m.client.Chat.Completions.NewStreaming(ctx, req)
	var chunkError error
	contentChunks, reasoningChunks := 0, 0
	for stream.Next() {
		chunk := stream.Current()
		content, reasoning, err := acc.addChunk(chunk, m.reasoning)
		if m.streamContent != nil && content != "" {
			contentChunks++
			m.streamContent(content, contentChunks, false)
		}
		if m.streamReasoning != nil && reasoning != "" {
			reasoningChunks++
			m.streamReasoning(reasoning, reasoningChunks, false)
		}
		if chunkError == nil && err != nil {
			chunkError = err
		}
	}
	if len(acc.ChatCompletion.Choices) > 0 && acc.ChatCompletion.Choices[0].Message.Content != "" {
		m.streamContent("", contentChunks, true)
	}
	return acc, errors.Join(stream.Err(), chunkError)
}

// Modified accumulator which will also get reasoning content
type accumulator struct {
	openai.ChatCompletionAccumulator
	reasoning string
}

func (a *accumulator) addChunk(chunk openai.ChatCompletionChunk, reasoningField string) (content, reasoning string, err error) {
	a.AddChunk(chunk)
	if fld, ok := chunk.JSON.ExtraFields["timings"]; ok {
		a.ChatCompletion.JSON.ExtraFields = map[string]respjson.Field{"timings": fld}
	}
	if len(chunk.Choices) > 0 {
		choice := chunk.Choices[0].Delta
		content = choice.Content + choice.Refusal
		if fld, ok := choice.JSON.ExtraFields[reasoningField]; ok && fld.Raw() != "" {
			reasoning, err = strconv.Unquote(fld.Raw())
			a.reasoning += reasoning
		}
	}
	return
}

// Create chat completion parameters in openai format for use by generate
func (m *Model) newRequest(cfg Config, messages []Message) (req openai.ChatCompletionNewParams, err error) {
	req.Model = m.id
	req.Seed = cfg.Seed
	req.Temperature = cfg.Temperature
	req.TopP = cfg.TopP
	if cfg.TopK.Valid() {
		util.SetExtraField(&req, "top_k", cfg.TopK.Value)
	}
	req.PresencePenalty = cfg.PresencePenalty
	if cfg.RepetitionPenalty.Valid() {
		util.SetExtraField(&req, "repetition_penalty", cfg.RepetitionPenalty.Value)
	}
	if m.server == "llamacpp" || m.server == "vllm" {
		if cfg.ReasoningEffort == "none" {
			util.SetExtraField(&req, "chat_template_kwargs", map[string]any{"enable_thinking": false})
		} else if cfg.ReasoningEffort != "" {
			req.ReasoningEffort = cfg.ReasoningEffort
			util.SetExtraField(&req, "chat_template_kwargs", map[string]any{"reasoning_effort": cfg.ReasoningEffort})
		}
	}
	for _, def := range cfg.Tools {
		fn := &openai.ChatCompletionFunctionToolParam{
			Function: shared.FunctionDefinitionParam{
				Name:        def.Name,
				Description: openai.String(def.Description),
				Parameters:  def.Parameters,
			},
		}
		req.Tools = append(req.Tools, openai.ChatCompletionToolUnionParam{OfFunction: fn})
	}
	if len(cfg.Tools) > 0 && !cfg.DisableParallelToolCalls {
		req.ParallelToolCalls = openai.Bool(true)
	}

	lastUserMessage := -1
	for i := len(messages) - 1; i >= 0; i-- {
		if messages[i].Role == "user" {
			lastUserMessage = i
			break
		}
	}
	for i, msg := range messages {
		var m openai.ChatCompletionMessageParamUnion
		switch msg.Role {
		case "system":
			m = openai.SystemMessage(msg.Content)
		case "user":
			m = openai.UserMessage(msg.Content)
		case "assistant":
			m = openai.AssistantMessage(msg.Content)
			if msg.Reasoning != "" && i > lastUserMessage {
				util.SetExtraField(m.OfAssistant, "reasoning_content", msg.Reasoning)
			}
			for _, call := range msg.ToolCalls {
				toolCall := openai.ChatCompletionMessageToolCallUnionParam{
					OfFunction: &openai.ChatCompletionMessageFunctionToolCallParam{
						ID: call.ID,
						Function: openai.ChatCompletionMessageFunctionToolCallFunctionParam{
							Name:      call.Name,
							Arguments: call.Arguments,
						},
					},
				}
				m.OfAssistant.ToolCalls = append(m.OfAssistant.ToolCalls, toolCall)
			}
		case "tool":
			m = openai.ToolMessage(msg.Content, msg.ToolCallID)
		default:
			return req, fmt.Errorf("invalid message role %q", msg.Role)
		}
		req.Messages = append(req.Messages, m)
	}
	return req, nil
}

func getError(rawJSON string) error {
	type errorResponse struct {
		Code    int
		Message string
	}
	v := errorResponse{Code: 500, Message: "server error"}
	if err := json.Unmarshal([]byte(rawJSON), &v); err != nil {
		return err
	}
	return fmt.Errorf("error %d: %s", v.Code, v.Message)
}
